### ISSUE TITLE
url的json格式不能自动解析

### ISSUE THREAD

**Issue by AndyDUT** [WeBankBlockchain/Truora-Service#62]
使用
json(https://api.exchangerate-api.com/v4/latest/CNY).rates.JPY
总是提示
Fail
（Unknown unexpected exception:[ConnectException: Network is unreachable (connect failed)].）
这个格式的url是否可以自动解析

**Comment by yanyanho** [comment]
网络连接问题导致的。实际url是这个：https://api.exchangerate-api.com/v4/latest/CNY

**Comment by AndyDUT** [comment]
> 网络连接问题导致的。实际url是这个：https://api.exchangerate-api.com/v4/latest/CNY

请求类型：
链下API接口
请求地址:
json(https://api.exchangerate-api.com/v4/latest/CNY).rates.JPY
用户合约地址：
0xad5d2725b3cedb045ef2e944a05872218d7092d1
处理时长：
4934 ms
请求状态：
Fail
（Unknown unexpected exception:[ConnectException: Network is unreachable (connect failed)].）

**Comment by AndyDUT** [comment]
> 网络连接问题导致的。实际url是这个：https://api.exchangerate-api.com/v4/latest/CNY

浏览器可以打开上述url，但合约中
url = "json(https://api.exchangerate-api.com/v4/latest/CNY).rates.JPY";
这个url的写法好像不能正确解析

**Comment by yanyanho** [comment]
可以的，你在fisco bcos或者webankblockchain开发群里吗？可以在群里提出问题。

**Comment by yanyanho** [comment]
你的服务器是不是无法访问网络？

**Comment by AndyDUT** [comment]
> 你的服务器是不是无法访问网络？

可以正常使用天气API，json解析应该是没有问题的，有可能是网络的问题
