### ISSUE TITLE
truora/deploy/key/ECC/keyStoreUser.txt 中的账户publicKey兼容压缩标示

### ISSUE THREAD

**Issue by zzyongx** [WeBankBlockchain/Truora-Service#86]
**背景**
如果bcos启用了权限，则可能需要修改truora/deploy/key/ECC/keyStoreUser.txt以配置账号，在填写publicKey时，容易把publicKey的压缩标示（04）带上。导致VRF预言机服务创建失败。

**待解决的问题**
兼容publicKey的压缩标示，或在文档中特别说明。

**使用场景**
用户修改keyStoreUser.txt时。

**功能列表**
兼容publicKey未压缩标示（04）

**兼容性**
需要兼容publicKey不带压缩标示的情况

**版权豁免声明**
所有的CIP必须自愿放弃版权。

**Comment by yanyanho** [comment]
感谢体验，已经排入迭代计划。
