### ISSUE TITLE
Truora预言机调用getRandomNumber获取随机数异常

### ISSUE THREAD

**Issue by dengzhh** [WeBankBlockchain/Truora-Service#88]
**BUG描述**
通过WeBase-Front编译部署示例合约RandomNumberSampleVRF之后，调用合约函数getRandomNumber成功返回，但是查询历史中返回的随机数结果为空。truora-service容器日志返回如下异常：
2021-05-12 17:02:33.337 [sdkThreadPool-2] INFO  LibVRFK1(:) - Load vrf lib from:[/dist/conf/libvrfjna.so]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OddLength', src/lib.rs:32:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

**重现方式**
采用官方文档的一键部署。

**预期结果**
无异常。

**截图**
如果可行，放上截图便于更具体地描述BUG。

**环境**
 - 操作系统: CentOS
 - 版本: CentOS Linux release 7.8.2003 (Core)，docker-ce-19.03.13-3

**更多信息**
关于该 BUG 的更多信息

**Comment by yanyanho** [comment]
vrf rust动态库生成会校验私钥长度，如果奇数位则报错。 后续我们我加上校验。
