### ISSUE TITLE
0.4版本VRFCore合约编译错误

### ISSUE THREAD

**Issue by dengzhh** [WeBankBlockchain/Truora-Service#89]
**BUG描述**
0.4版本VRFCore合约编译错误

**重现方式**
使用官方文档介绍的一键部署方式部署Truora后，进入WeBase-Front的合约IDE界面，导入合约目录“Truora-Service\contracts\1.0\sol-0.4\oracle\simple-vrf”下的所有合约文件，选择编译器版本“v0.4.25”，然后编译VRFCore.sol，出现以下编译错误：
合约未编译或编译失败
1、{ "component": "general", "formattedMessage": "VRF.sol:97:13: CompilerError: Stack too deep, try removing local variables.\n _publicKey[1]);\n ^--------^\n", "message": "Compiler error (/root/project/libsolidity/codegen/LValue.cpp:49):Stack too deep, try removing local variables.", "severity": "error", "sourceLocation": { "end": 4161, "file": "VRF.sol", "start": 4151 }, "type": "CompilerError" }

**预期结果**
无错误

**Comment by yanyanho** [comment]
使用0.6版本合约即可。
